/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Resume_uploadRouteImport } from './routes/resume_upload'
import { Route as CommandsSectionRouteImport } from './routes/CommandsSection'
import { Route as IndexRouteImport } from './routes/index'

const Resume_uploadRoute = Resume_uploadRouteImport.update({
  id: '/resume_upload',
  path: '/resume_upload',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandsSectionRoute = CommandsSectionRouteImport.update({
  id: '/CommandsSection',
  path: '/CommandsSection',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/CommandsSection': typeof CommandsSectionRoute
  '/resume_upload': typeof Resume_uploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/CommandsSection': typeof CommandsSectionRoute
  '/resume_upload': typeof Resume_uploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/CommandsSection': typeof CommandsSectionRoute
  '/resume_upload': typeof Resume_uploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/CommandsSection' | '/resume_upload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/CommandsSection' | '/resume_upload'
  id: '__root__' | '/' | '/CommandsSection' | '/resume_upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandsSectionRoute: typeof CommandsSectionRoute
  Resume_uploadRoute: typeof Resume_uploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume_upload': {
      id: '/resume_upload'
      path: '/resume_upload'
      fullPath: '/resume_upload'
      preLoaderRoute: typeof Resume_uploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CommandsSection': {
      id: '/CommandsSection'
      path: '/CommandsSection'
      fullPath: '/CommandsSection'
      preLoaderRoute: typeof CommandsSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandsSectionRoute: CommandsSectionRoute,
  Resume_uploadRoute: Resume_uploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
